baseURL = 'https://iotforge.io/'
languageCode = 'en-us'
title = 'IoT Forge'
theme = 'PaperMod'
mainSections = ['podcasts', 'articles']
sectionPagesMenu = 'main'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

# Add external menu entries
[menu]
  [[menu.main]]
  name = "YouTube"
  url = "https://www.youtube.com/@IoTForge"
  weight = 50
  pre = "<i class='fab fa-youtube'></i>"
  identifier = "youtube"

  [[menu.main]]
  name = "Podcast platforms"
  url = "https://creators.spotify.com/pod/profile/iot-forge/"
  weight = 60
  pre = "<i class='fab fa-spotify'></i>"
  identifier = "spotify"
