baseURL = 'https://iotforge.io/'
languageCode = 'en-us'
title = 'IoT Forge'
theme = 'PaperMod'
mainSections = ['podcasts', 'articles', 'resources']
sectionPagesMenu = 'main'
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[params]
ShowPostNavLinks = true
ShowBreadCrumbs = true

# Add external menu entries
[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Telegram"
url = "https://t.me/IoTForge"
weight = 14
pre = "<i class='fa-brands fa-telegram'></i>&nbsp;"
identifier = "telegram"

[[menu.main]]
name = "YouTube"
url = "https://www.youtube.com/@IoTForge"
weight = 50
pre = "<i class='fa-brands fa-youtube'></i>&nbsp;"
identifier = "youtube"

[[menu.main]]
name = "Podcast platforms"
url = "https://creators.spotify.com/pod/profile/iot-forge/"
weight = 60
pre = "<i class='fa-brands fa-spotify'></i>&nbsp;"
identifier = "spotify"
